Make content wider, Update some pages
tidev/titanium-docs pull request #186
Opened 2023-04-09 13:41 UTC by m1ga

* increase content width from 740px to 900px (wider makes it a bit harder to read, lines are too long)
* fixed https://titaniumsdk.com/guide/Alloy_Framework/Alloy_Guide/Alloy_Concepts.html#alloy-and-the-titanium-sdk table
* removed some `warning` blocks
* removed some `download` images (those big green down arrows)
* cleaned up Compatibility matrix
* removed version numbers from https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Getting_Started/Prerequisites/ and linked to Compatibility matrix right away. So we only have to maintain one list of version numbers
* updated links in https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Guide/Welcome_To_Titanium/Titanium_Resources.html

To see the real page you can use the `Preview rich diff` (the :page_facing_up: icon on the top right side of the file view) to see the differences in markdown mode.

2023-05-13 16:35 UTC, cb1kenobi requested changes

2023-05-13 16:35 UTC, cb1kenobi commented on docs/guide/Titanium_SDK/Titanium_SDK_Getting_Started/Installation_and_Configuration/Installing_Titanium_Advanced_Tools/README.md
> +If you build a module for the first time the CLI will automatically download a JDK version for you.
NDK, not JDK :)

2023-05-13 17:06 UTC, cb1kenobi commented on docs/guide/Titanium_SDK/Titanium_SDK_Guide/Titanium_SDK_Open_Source_Attribution_Notice.md
> -Up-to-date information is available at [http://www.appcelerator.com/opensource/](http://www.appcelerator.com/opensource/).
At this point, just delete this file and any incoming links.

2023-05-13 17:07 UTC, cb1kenobi commented on docs/guide/Titanium_SDK/Titanium_SDK_Guide/Welcome_To_Titanium/Titanium_Resources.md
> +### Developer resources, Help and support
```suggestion
### Developer Resources, Help, and Support
```

2023-05-13 18:07 UTC, m1ga commented
Updated the last parts:
* removed all gperf/git links and pages
* jdk -> ndk mistake
* adjusted the headline on the support page

2023-05-20 13:40 UTC, cb1kenobi approved these changes

2023-05-20 13:40 UTC, merged