fix: manually configure purgecss
tidev/titanium-docs pull request #20
Opened 2020-10-10 12:21 UTC by janvennemann

2020-10-19 14:59 UTC, sgtcoolguy requested changes

2020-10-19 14:59 UTC, sgtcoolguy commented on docs/.vuepress/plugins/purgecss.js
> +      `${sizrceDir}/../website/pages/**/*.md`,
I assume these are typos?
```suggestion
      `${sourceDir}/../website/pages/**/*.md`,
```

2020-10-19 14:59 UTC, sgtcoolguy commented on docs/.vuepress/plugins/purgecss.js
> +      `${sizrceDir}/../website/pages/**/*.vue`
```suggestion
      `${sourceDir}/../website/pages/**/*.vue`
```

2020-10-19 14:59 UTC, sgtcoolguy commented on docs/.vuepress/plugins/purgecss.js
> +    defaultExtractor: context => {
```suggestion
    defaultExtractor: content => {
```

2020-10-19 15:15 UTC, sgtcoolguy commented
I commented out the guard to not run purges on dev builds and tried this still results in a mangled UI with seemingly no CSS.

2020-10-19 21:04 UTC, janvennemann commented
@sgtcoolguy i updated the globs to include all VuePress plugins and our theme, it should keep all used CSS now

2020-10-20 15:17 UTC, sgtcoolguy commented
Well, we're closer - but something still seems funky. I tried this locally rebased on master, and the external link markers get... interesting:
<img width="222" alt="Screen Shot 2020-10-20 at 11 16 36 AM" src="https://user-images.githubusercontent.com/3252/96606878-c2251700-12c5-11eb-8a6c-adcbadf2fe0d.png">
<img width="357" alt="Screen Shot 2020-10-20 at 11 16 44 AM" src="https://user-images.githubusercontent.com/3252/96606914-c9e4bb80-12c5-11eb-8c62-838659f4ae50.png">

2020-10-20 17:29 UTC, sgtcoolguy commented
ok, figured it out, needed to include `node_modules/@vuepress/core/lib/**/*.vue`

2020-10-20 17:29 UTC, sgtcoolguy approved these changes

2020-10-20 18:23 UTC, merged